name: mockito_analyzer_plugin
description: An analyzer plugin with guard rails for using mockito
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  analysis_server_plugin: ^0.3.0
  analyzer: ^8.4.0
  analyzer_plugin: ^0.13.6
  collection: ^1.19.0

dev_dependencies:
  analyzer_testing: ^0.1.2
  test: ^1.26.0
  test_reflective_loader: ^0.3.0

